coverage:
  status:
    project:
      unit:
        target: auto
        flags:
          - unitTest
      integration:
        target: auto
        flags:
          - integrationTest
flags:
  unitTest:
    paths:
      - src/main/java/com/gg/server/
  integrationTest:
    paths:
      - src/main/java/com/gg/server/