coverage:
  status:
    project:
      unit:
        target: 5%
        flags:
          - unitTest
      integration:
        target: 60%
        flags:
          - integrationTest
flags:
  unitTest:
    paths:
      - gg-pingpong-api/src/main/java/gg/pingpong/api
      - gg-pingpong-repo/src/main/java/gg/pingpong/repo
      - gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo
      - gg-pingpong-data/src/main/java/gg/pingpong/data
  integrationTest:
    paths:
      - gg-pingpong-api/src/main/java/gg/pingpong/api
      - gg-pingpong-repo/src/main/java/gg/pingpong/repo
      - gg-pingpong-admin-repo/src/main/java/gg/pingpong/admin/repo
      - gg-pingpong-data/src/main/java/gg/pingpong/data
