coverage:
  status:
    project:
      unit:
        target: 5%
        flags:
          - unitTest
      integration:
        target: 60%
        flags:
          - integrationTest
flags:
  unitTest:
    paths:
      - gg-pingpong-api/src/main/java/gg/pingpong/api
      - gg-repo/src/main/java/gg/repo
      - gg-admin-repo/src/main/java/gg/admin/repo
      - gg-data/src/main/java/gg/data
      - gg-auth/src/main/java/gg/auth
      - gg-utils/src/main/java/gg/utils
  integrationTest:
    paths:
      - gg-pingpong-api/src/main/java/gg/pingpong/api
      - gg-repo/src/main/java/gg/repo
      - gg-admin-repo/src/main/java/gg/admin/repo
      - gg-data/src/main/java/gg/data
      - gg-auth/src/main/java/gg/auth
      - gg-utils/src/main/java/gg/utils
